### ISSUE TITLE
Standalone Applications

### ISSUE THREAD

**Issue by xaviervilla** [kaueraal/run_scaled#10]
I am using Mars4_5.jar to program in Mips for a class. My Surface Book has very high DPI and close to 4K resolution. recursive binary search and bubblesort in Mips isn't easy, but reading memory addresses the size a a human hair makes it much harder. I digress. I got this script working on Firefox easily, but I can't figure out how to run it with my standalone application Mars4_5.jar.

The command I use regularly to run Mars is:
`java -jar Mars4_5.jar`

I have tried this without success:
`./run_scaled "java -jar Mars4_5.jar"`
and also:
`./run_scaled "java -jar /full/directory/path/Mars4_5.jar"`

What is the best way to get this script working with my application?

Thank you

**Comment by xaviervilla** [comment]
I thought maybe if I added an alias for my purpose, and used the one-word alias, it would work. But it didn't. Here's what I tried.
I added the following alias in bashrc
`mars = 'java -jar Mars4_5.jar'`
and I confirmed that `mars` worked from any directory.
Then i navigated to my run_scaled script, and ran
`./run_scaled mars`
but this did not work either.
Here is the output:
`./run_scaled mars
Warning: invalid option: 'scaling'
2018-04-25 11:52:38,336 server failure: disconnected before the session could be established
2018-04-25 11:52:38,336 server requested disconnect: server error (failed to start a new session)
Warning: cannot use the system proxy for 'start' subcommand,
 FAILURE
Warning: invalid option: 'scaling'
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:79648619.log
Warning: invalid option: 'scaling'
2018-04-25 11:52:40,763 Xpra gtk2 client version 2.2.6-r18968 64-bit
2018-04-25 11:52:40,763  running on Linux Ubuntu 16.04 xenial
Warning: invalid option: 'scaling'
2018-04-25 11:52:41,685 GStreamer version 1.8.3 for Python 2.7.12 64-bit
2018-04-25 11:52:41,965 No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
2018-04-25 11:52:41,970 Unable to load registered array format handler numeric:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/numeric.py", line 15, in <module>
    raise ImportError( """No Numeric module present: %s"""%(err))
ImportError: No Numeric module present: No module named Numeric

2018-04-25 11:52:41,970 Unable to load registered array format handler vbo:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

2018-04-25 11:52:41,970 Unable to load registered array format handler vbooffset:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

2018-04-25 11:52:42,040 Error: gtkgl rendering failed its sanity checks:
2018-04-25 11:52:42,040  PyOpenGL version 3.0.2 is too old and buggy
2018-04-25 11:52:42,073 OpenGL support is missing:
2018-04-25 11:52:42,073  No module named _types
xpra initialization error:
 cannot find live server for display :79648619
Warning: invalid option: 'scaling'
xpra initialization error:
 cannot find live server for display :79648619
`

**Comment by morunas** [comment]
Hi there. Your output seems to indicate issues with OpenGL. Have you tried running

`./run_scaled --opengl=no mars`

**Comment by xaviervilla** [comment]
Yes, but to no avail. 
Here is the output: 
```
$ ./run_scaled --opengl=no mars
2018-04-27 14:25:13,906 server failure: disconnected before the session could be established
2018-04-27 14:25:13,907 server requested disconnect: server error (failed to start a new session)
Warning: cannot use the system proxy for 'start' subcommand,
 FAILURE
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/:85035795.log
2018-04-27 14:25:16,334 Xpra gtk2 client version 2.2.6-r18968 64-bit
2018-04-27 14:25:16,334  running on Linux Ubuntu 16.04 xenial
2018-04-27 14:25:17,242 GStreamer version 1.8.3 for Python 2.7.12 64-bit
xpra initialization error:
 cannot find live server for display :85035795
xpra initialization error:
 cannot find live server for display :85035795
```
I should note that yesterday I completely reinstalled Ubuntu, so the output won't be the same. I also installed the python netifaces package that I was missing which seemed to clean up the output a lot.

**Comment by xaviervilla** [comment]
After viewing /run/user/1000/xpra/:85035795.log, I am going to try some things..

**Comment by morunas** [comment]
I would just like to state that I'm not savvy in these matters :) but as I've myself been using run_scaled and struggling with some details here and there I guess I can try and give my 2 cents as to what to pursue.

I'd like to point the following entry from your log:
`/bin/sh: 1: mars: not found`
I'd suggest creating a shell script that runs your initialization command (a mars.sh file) and then passing either the full path to that script or adding it to PATH

Also I'm not sure (don't understand) if all three sockets need to be created but your log also claims that the socket under /run/xpra couldn't be created due to user 'username' missing 'xpra' group membership. But I'd first try at least making sure that some command line executable is found before going into more log details.
